#!/usr/bin/env Rscript

require(docopt)
require(methods)

"
Usage:
BatchFlowTypeDataPrep.R (-h | --help | --version)
BatchFlowTypeDataPrep.R DIR

Description:   This script creates serialized Rdata files for the purposes of running FlowType in a batched manner
Options:
--version       Show the current version.

Arguments:

DIR    Provide directory for cytools.args.Rdata to be found, automatically generated by invoking cyttools.R
" -> doc


args <- docopt(doc)

ARGS_DIR <- args$DIR

cat("\nLoading arguments from", ARGS_DIR, "\n")

load(paste(ARGS_DIR, "cyttools.args.Rdata", sep = ""))

RESULTS_DIR <- args$OUT

source("cyttoolsFunctions.R")

dir <- args$DIR # grabs directory from initial cyttools call
file <- list.files(dir ,pattern='.fcs$', full=TRUE) # captures all FCS files in the directory

targets <- read.delim(args$PANEL)
colsToCheck <- c("Ignore", "TransformCofactor", "Lineage", "Functional", "NRS")
if(checkDesignCols(targets, colsToCheck)){
  missingCols <- colsToCheck[which(colsToCheck %in% colnames(targets) == F)]
  cat("\n\nERROR: PANEL file does not include required columns.
      \n\nMissing Columns:", missingCols,
      "\n\nPlease run cyttools.R --makePanelBlank and cyttools.R --computeNRS to generate compatible panel file.\n\nStopping cyttools.R\n\n")
  q()
}


lineage_markers <- targets$name[targets$Lineage == 1]
functional_markers <- targets$name[targets$Functional == 1]

if(args$transform == T){
  flowSet.trans <- read.flowSet.transVS(targets, file)
}else{
  flowSet.trans <- read.flowSet(file)
}

# order the markers using NRS, dropping markers set to "1" in Ignore column of panel design
lineage_markers_ord <- targets$name
lineage_markers_ord <- lineage_markers_ord[lineage_markers_ord %in% targets$name[which(targets$Ignore == 0)]]
lineage_markers_ord <- lineage_markers_ord[order(targets$NRS[which(targets$name %in% lineage_markers_ord)], decreasing = T)]

PartitionsPerMarker <- 2
MaxMarkersPerPop <- length(lineage_markers_ord)
MemLimit <- 16
MemUse <- 0
NumMarkers <- 1

while(MemLimit > MemUse){
  NumMarkers <- NumMarkers + 1
  MemUse <- calcMemUse(calcNumPops(PartitionsPerMarker, NumMarkers),
                     NumMarkers,
                     NumMarkers, 
                     max(fsApply(flowSet.trans, nrow)),
                     NumMarkers,
                     max(PartitionsPerMarker))/10^9
}

NumMarkers <- NumMarkers - 1

lineage_markers_ord <- lineage_markers_ord[1:NumMarkers]

colsToUse <- which(targets$name %in% lineage_markers_ord == T)

dir.create(paste(RESULTS_DIR, "BatchFlowTypeDataPrepWorkspaces/", sep = ""), showWarnings = F, recursive = T)
for ( i in 1:length(flowSet.trans)){
  batchWorkspaceFile <- paste(RESULTS_DIR, "BatchFlowTypeDataPrepWorkspaces/BatchFlowTypeDataPrepWorkspace_", i, ".Rdata", sep = "")
  ffb <- flowSet.trans[[i]]
  parameters(ffb)$desc <- targets$desc
  ffb <- ffb[,colsToUse]
  save(ffb, file = batchWorkspaceFile)
}

# workspaceFile <- paste(RESULTS_DIR, "FlowTypeWorkspace.Rdata", sep = "")
# 
# save.image(file = workspaceFile)