#!/usr/bin/env Rscript

require(docopt)
require(methods)

"
Usage:
FlowType.R (-h | --help | --version)
FlowType.R DIR PANEL

Description:   This script applies the flowType algorthim to high parameter cytometry data
Options:
--version       Show the current version.

Arguments:

DIR    Provide directory for cytools.args.Rdata to be found, automatically generated by invoking cyttools.R
PANEL  Provide a panel design file, use --makePanelBlank to generate and edit as needed
" -> doc


args <- docopt(doc)

RESULTS_DIR <- args$DIR

cat("\nLoading arguments from", args$DIR, "\n")

load(paste(RESULTS_DIR, "cyttools.args.Rdata", sep = ""))

library(flowCore)
library(cytofCore)
library(flowVS)
library(flowType)
library(tidyverse)
library(reshape2)

dir <- args$DIR # grabs directory from initial cyttools call
file <- list.files(dir ,pattern='.fcs$', full=TRUE) # captures all FCS files in the directory
flowSet <- read.flowSet(file, transformation = F) # reads in files as flowSet, required for flowType

targets <- read.delim(args$PANEL)

lineage_markers <- targets$name[targets$Lineage == 1]
functional_markers <- targets$name[targets$Functional == 1]

flowSet.trans <- transFlowVS(flowSet, 
                             as.character(targets$name[which(targets$Lineage == 1 |
                                                               targets$Functional == 1)]),
                             rep(5, length(targets$name[which(targets$Lineage == 1 |
                                                                targets$Functional == 1)])))


ResList <- flowType(flowSet.trans[[1]],
                    PropMarkers = lineage_markers_ord[1:12],
                    MFIMarkers = lineage_markers_ord[1:12],
                    MarkerNames = targets$desc[targets$name %in% lineage_markers_ord[1:12]],
                    MemLimit = 15)



fsApply(flowSet.trans, 'flowType', 
        PropMarkers = lineage_markers,
        MFIMarkers = lineage_markers,
        MarkerNames = targets$desc[which(targets$Lineage == 1)],
        MaxMarkersPerPop = 14,
        MemLimit = 15)



