#!/usr/bin/env Rscript

require(docopt)
require(methods)

"
Usage:
MakePanelBlank.R (-h | --help | --version)
MakePanelBlank.R DIR

Description:   This script generates a blank panel file based on a directory of FCS files
Options:
--version       Show the current version.

Arguments:

DIR    Provide directory for cytools.args.Rdata to be found, automatically generated by invoking cyttools.R
" -> doc


args <- docopt(doc)

RESULTS_DIR <- args$DIR

cat("\nLoading arguments from", args$DIR, "\n")

load(paste(RESULTS_DIR, "cyttools.args.Rdata", sep = ""))

library(flowCore)
library(cytofCore)
library(flowVS)
library(flowType)
library(tidyverse)
library(reshape2)

dir <- args$DIR # grabs directory from initial cyttools call
file <- list.files(dir ,pattern='.fcs$', full=TRUE) # captures all FCS files in the directory
flowSet <- read.flowSet(file, transformation = F) # reads in files as flowSet, required for flowType

save.image(file = "~/BTSync/FLOW_CORE/cyttools/MakePanelBlank.Rdata")