#!/usr/bin/env Rscript

require(docopt)
require(methods)

"
Usage:
MakePanelBlank.R (-h | --help | --version)
MakePanelBlank.R DIR

Description:   This script generates a blank panel file based on a directory of FCS files
Options:
--version       Show the current version.

Arguments:

DIR    Provide directory for cytools.args.Rdata to be found, automatically generated by invoking cyttools.R
" -> doc


args <- docopt(doc)

ARGS_DIR <- args$DIR

cat("\nLoading arguments from", ARGS_DIR, "\n")

load(paste(ARGS_DIR, "cyttools.args.Rdata", sep = ""))

source("cyttoolsFunctions.R")

panelColnames <- c("name", "desc", "range", "minRange", "maxRange", "TransformCofactor", "Ignore", "Lineage", "Functional", "Barcode", "Viability", "EventDiscrimination", "EQBEADS")

dir <- args$DIR # grabs directory from initial cyttools call
file <- list.files(dir ,pattern='.fcs$', full=TRUE) # captures all FCS files in the directory
flowSet <- read.flowSet(file, transformation = F) # reads in files as flowSet, required for flowType

panel <- as.data.frame(pData(parameters(flowSet[[1]])))
panelBlank <- panel

for ( i in c((ncol(panel)+1):length(panelColnames))){
  panelBlank <- cbind(panelBlank, rep(0, nrow(panelBlank)))
}

colnames(panelBlank) <- panelColnames
panelBlank$TransformCofactor <- rep(5, nrow(panelBlank))

RESULTS_DIR <- args$OUT
panelFile <- paste(RESULTS_DIR, "panelFile.txt", sep = "")

write.table(panelBlank, file = panelFile, sep = "\t", quote = F, row.names = F)
