#!/usr/bin/env Rscript

require(docopt)
require(methods)

"
Usage:
MakePanelBlank.R (-h | --help | --version)
MakePanelBlank.R DIR

Description:   This script generates a blank panel file based on a directory of FCS files
Options:
--version       Show the current version.

Arguments:

DIR    Provide directory for cytools.args.Rdata to be found, automatically generated by invoking cyttools.R
" -> doc


args <- docopt(doc)

ARGS_DIR <- args$DIR

cat("\nLoading arguments from", ARGS_DIR, "\n")

load(paste(ARGS_DIR, "cyttools.args.Rdata", sep = ""))

source("cyttoolsFunctions.R")

panelColnames <- c("name", "desc", "range", "minRange", "maxRange", "TransformCofactor", "Ignore", "Lineage", "Functional", "Barcode", "Viability", "EventDiscrimination", "EQBEADS")

dir <- args$DIR # grabs directory from initial cyttools call
file <- list.files(dir ,pattern='.fcs$', full=TRUE) # captures all FCS files in the directory
flowSet <- read.ncdfFlowSet(file) # reads in files as flowSet, required for flowType

panel <- as.data.frame(pData(parameters(flowSet[[1]])))
panelBlank <- panel

for ( i in c((ncol(panel)+1):length(panelColnames))){
  panelBlank <- cbind(panelBlank, rep(0, nrow(panelBlank)))
}

colnames(panelBlank) <- panelColnames
panelBlank$TransformCofactor <- rep(5, nrow(panelBlank))

panel <- panelBlank

panel$EQBEADS[grep("EQBEADS", panel$desc)] <- 1
panel$Barcode[grep("Pd", panel$desc)] <- 1
panel$EventDiscrimination[grep("Ir", panel$desc)] <- 1
panel$Viability[grep("Pt", panel$desc)] <- 1

panel$descOriginal <- panel$desc

panel$desc <- gsub("^[0-9]{2,3}.{1,2}\\_|-EQBEADS", "", panel$desc)

panel$metal <- gsub("Di", "", panel$name)
panel$mass <- gsub("[A-z]*", "", panel$metal)
panel$element <- gsub("[0-9]*", "", panel$metal)
panel$nameCheck <- paste0(panel$mass, panel$element)  

panel$Ignore[which(panel$nameCheck == panel$desc)] <- 1
panel$Ignore[which(panel$Barcode == 1)] <- 1
panel$Ignore[grep("EQBEADS|dist", panel$desc)] <- 1
panel$Ignore[is.na(panel$desc)] <- 1
panel$Ignore[which(panel$Viability == 1)] <- 1
panel$Ignore[which(panel$EventDiscrimination == 1)] <- 1

functionalMarkerIndex <- grep("p", panel$desc)
panel$Functional[functionalMarkerIndex] <- 1

knownFunctionalMarkers <- c("Tbet", "FOXP3", "IKBA", "GRANZYME_B", "PERFORIN")

panel$Functional[panel$desc %in% knownFunctionalMarkers] <- 1

panel$Lineage[panel$Ignore == 0 & panel$Functional == 0] <- 1


RESULTS_DIR <- args$OUT
panelFile <- paste(RESULTS_DIR, "panelFile.txt", sep = "")

write.table(panel, file = panelFile, sep = "\t", quote = F, row.names = F)
