#!/usr/bin/env Rscript

require(docopt)
require(methods)

"
Usage:
makeMetaDataBlank.R (-h | --help | --version)
makeMetaDataBlank.R DIR

Description:   This script is makes meta data table blanks for use with cyttools.
Options:
--version       Show the current version.

Arguments:

DIR    Provide directory for cytools.args.Rdata to be found, automatically generated by invoking cyttools.R
" -> doc


args <- docopt(doc)

ARGS_DIR <- args$DIR

cat("\nLoading arguments from", ARGS_DIR, "\n")

load(paste(ARGS_DIR, "cyttools.args.Rdata", sep = ""))

source("cyttoolsFunctions.R")

# USER SHOULD BE PASSING THIS IN AS A SEPARATE FILE
dir <- args$DIR # grabs directory from initial cyttools call
file <- list.files(dir ,pattern='.fcs$', full=TRUE) # captures all FCS files in the directory

md <- file %>% 
  as.data.frame() %>%
  setNames(c("FileName")) %>%
  mutate(SampleID = vector(length = length(FileName)),
         Group = vector(length = length(FileName)),
         Condition = vector(length = length(FileName)),
         TimePoint = vector(length = length(FileName)))
  
  
RESULTS_DIR <- args$OUT      
mdFile <- paste(RESULTS_DIR, "MetaDataFile.txt", sep = "")

write.table(md, file = mdFile, sep = "\t", quote = F, row.names = F)
